export const APP_FEATURES = [
  {
    id: "01",
    title : "Tailored Just for You",
    description: "Get interview questions and model answers based on your role, experience, and specific focus areas"
  },


  {
    id: "02",
    title : "Learn at your Own Pace",
    description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed"
  },

  {
    id: "03",
    title : "Capture your Insights",
    description: "Add Personal notes to any questions and pin important ones to the top - making your learning more organize"
  },


    {
    id: "01",
    title : "Understand the 'Why' Behind Answers",
    description: "Beyond Just answers - unlock detailed concept explanantion generated by AI, helping you truly master each concept"
  },

      {
    id: "05",
    title : "Save , Organize , Revisit",
    description: "Easily save your interview sets, organize then nearly in your dashboard and pick up your preparation "
  },



]